import esbuild from "esbuild";
import sassPlugin from 'esbuild-sass-plugin';
import glsl from "esbuild-plugin-glsl";
import nodeExternals from "esbuild-plugin-node-externals";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this script
*/
`;

const prod = process.argv[2] === "production";

const esbuildConfig = {
    entryPoints: ["environment.ts"],
    plugins: [
        sassPlugin(),
        glsl({
            minify: true,
        }),
        nodeExternals({
            packagePaths: 'package.json',
            include: [
                './lib/*',
                './mode/*',
                './addon/*',
            ],
        }),
    ],
    bundle: true,
    external: [
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...require("builtin-modules")
    ],
    format: "cjs",
    target: "es6",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "./environment.js",
};

if (prod) {
    esbuild.build(esbuildConfig).catch(() => process.exit(1));
} else {
    esbuild.build({
        ...esbuildConfig,
        watch: true,
    }).then(() => console.log('Watching for changes...')).catch(() => process.exit(1));
}
