[tool.black]
exclude = '^(venv|.venv|venvs|env|build|dist)/'
line-length = 79 # Adjust to flake8
[tool.isort]
known_third_party = [yaml]  # Add external libraries hereprofile = "black" # Ensures compatibility with Black formatting
line_length = 79
skip_glob = ['venv/*', '.venv/*', 'venvs/*', 'env/*', 'build/*', 'dist/*']
[mypy]
disallow_untyped_calls = True
# Enforces type annotations
disallow_untyped_defines = True
exclude = ^(venv|.venv|venvs|env|build|dist)/
[tool.ruff]
exclude = ['venv', '.venv', 'venvs', 'env', 'build', 'dist']
[tool.pyink]
exclude = '^(venv|.venv|venvs|env|build|dist)/'
