[tool.black]
exclude = '^(venv|.venv|venvs|env|build|dist)/'
line-length = 79
# Adjust to flake8
[tool.isort]
line_length = 79
profile = "black"
# Ensures compatibility with Black formatting
skip_glob = ['venv/*', '.venv/*', '**venvs/*', '**/lib/*', 'env/*', 'build/*', 'dist/*']
[mypy]
disallow_untyped_calls = True
# Enforces type annotations
disallow_untyped_defines = True
exclude = ^(venv|.venv|venvs|env|build|dist)/
[tool.ruff]
exclude = ['venv', '.venv', 'venvs', 'env', 'build', 'dist']
[tool.pyink]
exclude = '^(venv|.venv|venvs|env|build|dist)/'
