[tool.black]
line-length = 79  # Adjust to flake8
[tool.isort]
profile = "black"  # Ensures compatibility with Black formatting
line_length = 79
known_third_party = [yaml]  # Add external libraries here
[mypy]
disallow_untyped_calls = True  # Enforces type annotations
disallow_untyped_defines = True
exclude = ^(venv|.venv|env|build|dist)/
