name: CodeQL Analysis

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  codeql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read language from file
      id: read-language
      run: |
        LANG=$(cat codeql-analytics.txt)
        echo "::set-output name=language::$LANG"
      shell: bash

    - name: Set up CodeQL
      uses: github/codeql-action/setup@v1
      with:
        languages: ${{ steps.read-language.outputs.language }}

    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v1

    - name: Upload CodeQL results
      uses: github/codeql-action/upload-sarif@v1
